### ISSUE TITLE
displayCondition returns true when expected false

### ISSUE THREAD

**Issue by tomerb15** [wix/wix-restaurants-js-sdk#11]
1. Using the latest version of the NPM.
2. `checkCondition({condition: section.displayCondition}` return true for a section that is defined to run at 15:00-18:00
3. Execution time: 13:25 Israel time.

The section id is: `-39.1510071652603`
The rest Id: `3222070773213117`

* When running `checkCondition` on the field `section.condition` i get the following exception:
`Cannot read property 'clone' of undefined`

**Comment by 3LOK** [comment]
You need to pass a momentjs parameter named 'deliveryTime'.

**Comment by tomerb15** [comment]
just a regular `moment()` ?

**Comment by 3LOK** [comment]
Should be configured with your time zone, but yes.

**Comment by tomerb15** [comment]
still getting true where i should get false.

Tried with both moment() and moment.tz()
`conditionHelper.checkCondition({condition: section.displayCondition, deliveryTime :moment.tz()})`
`conditionHelper.checkCondition({condition: section.displayCondition, deliveryTime :moment()})`

My computer is set to israel time, so it should have work.

Any ideas?
This time the section id is: `127191070` which is configured to be valid between 12:00-15:00
Test time: 16:02

**Comment by 3LOK** [comment]
displayCondition - When should the menu be displayed.
condition - When can someone order from the menu.

For example, dinner menu you want to display all the time for people to know, but let people order from it only during specific times.

You probably want condition and not displayCondition.

**Comment by tomerb15** [comment]
Seems to work as expected with `condition`
Thanks!
