### ISSUE TITLE
Callcenter Menu is still available to display.

### ISSUE THREAD

**Issue by tomerb15** [wix/wix-restaurants-js-sdk#12]
Hey,
I run the following two functions on a Menu that is a callcenter Menu:
`conditionHelper.checkCondition({condition: callcenter.condition, deliveryTime : moment().tz(timezone)})`
`conditionHelper.checkCondition({condition: callcenter.condition, deliveryTime : moment().tz(timezone)})`
Both returned the value `true` while `displayCondition` was expected to return `false`.

Here are the two properties `condition` and `displayCondition` of the callcenter object:

Condition:
![pastedgraphic-1](https://user-images.githubusercontent.com/14358353/36985473-023502e4-20a0-11e8-9293-a1f83294b483.png)

DisplayCondition:
![pastedgraphic-3](https://user-images.githubusercontent.com/14358353/36985482-0a7cdad0-20a0-11e8-8bf7-93035289ecb6.png)

MenuId: -40.1486051560583

* I'm using the latest version of this NPM.

**Comment by dleshem** [comment]
What's the restaurant ID?

**Comment by tomerb15** [comment]
rest ID: meatnight-florentin

**Comment by dleshem** [comment]
@3LOK Looks like these callcenter sections use the legacy

`"properties":{"com.openrest":"{\"refs\":[\"callcenter\"]}"}`

Should this be defined via an `order_platform` condition? Re-saving the menu had no effect.

**Comment by 3LOK** [comment]
@dleshem Sections look ok to me. 
@tomerb15 you didn't give any platform in his function call, so platform check is skipped. Are you web? mobileweb? ios? android?

**Comment by tomerb15** [comment]
I tried to pass the following platform:
`com.messenger`

Still true on both `condition` and `displayCondition`

These are the objects i used for the function call:

```
{condition: sections[i].displayCondition, deliveryTime : moment().tz(timezone), platform: "com.messenger"}
```
and
```
{condition: sections[i].condition, deliveryTime : moment().tz(timezone), platform: "com.messenger"}
```

**Comment by 3LOK** [comment]
It's true because the definition for these menus is to allow for that platform.
