### ISSUE TITLE
Infinite loop - availability issue

### ISSUE THREAD

**Issue by tomerb15** [wix/wix-restaurants-js-sdk#14]
Hey, when `store.openTimes.weekly` is set to:
```
[
    {minuteOfWeek: 0, durationMins: 1440},
    {minuteOfWeek: 1440, durationMins: 1440},
    {minuteOfWeek: 2880, durationMins: 1440},
    {minuteOfWeek: 4320, durationMins: 1440},
    {minuteOfWeek: 5760, durationMins: 1440},
    {minuteOfWeek: 7200, durationMins: 1440},
    {minuteOfWeek: 8640, durationMins: 1440}
]
```
I get an infinite loop on `it.next()` when i check if the store is available.

Here is the Availability check code:
```
var it = new availability.AvailabilityIterator({
            availability: availabilityObj,
            cal: moment.tz(timezone)
        });

        var test = it.next();
```

Note:
The `openTimes` array is representing a 24/7 open times.
I'm aware that i may set 24/7 with the following array:
```
[
{minuteOfWeek: 0, durationMins: 10080}
]
```
But still, i wasn't expecting the infinite loop from the above code.

**Comment by tomerb15** [comment]
If I'm reducing 1 min from the last index of the array, it works. EG:
```
[
    {minuteOfWeek: 0, durationMins: 1440},
    {minuteOfWeek: 1440, durationMins: 1440},
    {minuteOfWeek: 2880, durationMins: 1440},
    {minuteOfWeek: 4320, durationMins: 1440},
    {minuteOfWeek: 5760, durationMins: 1440},
    {minuteOfWeek: 7200, durationMins: 1440},
    {minuteOfWeek: 8640, durationMins: 1439}
]
```

**Comment by dleshem** [comment]
Does not reproduce.

Pasting the following code [here](https://npm.runkit.com/availability):

```
var AvailabilityIterator = require('availability').AvailabilityIterator;
var moment = require('moment-timezone');

var cal = moment.tz([2010, 12-1, 13, 0, 0, 0, 0], 'Asia/Jerusalem');
var availability = {
  weekly: [
    {minuteOfWeek: 0, durationMins: 1440},
    {minuteOfWeek: 1440, durationMins: 1440},
    {minuteOfWeek: 2880, durationMins: 1440},
    {minuteOfWeek: 4320, durationMins: 1440},
    {minuteOfWeek: 5760, durationMins: 1440},
    {minuteOfWeek: 7200, durationMins: 1440},
    {minuteOfWeek: 8640, durationMins: 1440}
  ],
  exceptions: []
};

var it = new AvailabilityIterator({ availability, cal });
console.log(it.next());
```

returns `Object {status: "available", until: null}`

If you can reproduce, please provide full code snippet.

**Comment by tomerb15** [comment]
Thanks, you are the best! after updating the Availability npm from `"availability": "^2.1.221"` to  `"availability": "^2.1.605"`

And "moment-timezone" from `"moment-timezone": "^0.5.5"` to `"moment-timezone": "^0.5.17"` it works as expected.

Prior to the update, your example wasn't working as well, which made me wonder about npm update
