### ISSUE TITLE
Search does't find store which has coordinates in its Polygons

### ISSUE THREAD

**Issue by tomerb15** [wix/wix-restaurants-js-sdk#15]
Hey, 
I can't get the api's search function to return a restaurant by giving it coordinates.

The following API call shall return the restaurant: `1601503664516685` But it returns nothing.

```
api.search({
            filter: {
                chainId: 3738946338482897,
                latLng: {
                    lat: -15.3570778,
                    lng: 28.2802687
                }
            }
```

The coordinates are inside the restaurant's delivery area, which is available.
The Restaurant is part of the chain.
It is open.
The Delivery Area is available as well.
Can you please help figure out why?
THanks!

**Comment by dleshem** [comment]
Fixed issue on our end. Thanks for reporting!
