### ISSUE TITLE
How to use search V2

### ISSUE THREAD

**Issue by tomerb15** [wix/wix-restaurants-js-sdk#16]
Hello,

I have used the following search request but it came back with an error. Can you please help me find what i have done wrong?

```
var api = require('wix-restaurants-js-sdk').clients.createRestClient();
api(`restaurants/delivering?lat=${options.filter.latLng.lat}&lng=${options.filter.latLng.lng}`,"post",{baseUrl: 'https://search.wixrestaurants.com/v1'},null).then(function(response){
                console.log(response);

            }).catch(function(e){
                console.log("ERROR ON SEARCH API CALL: " + e.detail);
            });
```

Thanks!

**Comment by dleshem** [comment]
Try the following:

`
const clients = require('wix-restaurants-js-sdk').clients;

const search = clients.createRestClient({baseUrl: 'https://search.wixrestaurants.com/v1'});

try {
  const {restaurantIds} = await search('/restaurants/delivering', 'get', {lat: 32.097150, lng: 34.774120});
  console.log(restaurantIds);
} catch (e) {
  console.log('ERROR', e);
}
`

**Comment by tomerb15** [comment]
OK Now it works, it seems like node 6 doesn't support Object.entries so i added an implementation for that.
