### ISSUE TITLE
chargeV2Helper.isApplicable - How does it work?

### ISSUE THREAD

**Issue by tomerb15** [wix/wix-restaurants-js-sdk#2]
I have a chargeV2 object with the following definition:
- 10% off ALL menu
- All other restrictions are irrelevant. (All platforms, During all working hours, on both delivery and peakup)

I would like to know which fields in the object passed to `chargeV2Helper.isApplicable` are relevant here?

What should i pass in case a certain condition is not relevant?

Thanks

**Comment by dleshem** [comment]
You can see the use case here: https://github.com/wix/wix-restaurants-js-sdk/blob/master/test/helpers/ChargeV2.test.js

Generally you should pass all requested fields, and let the implementation decide which is relevant.
