### ISSUE TITLE
condition for charge d6c84bf3-8c8a-497d-88cf-975c9b7face7 is not satisfied

### ISSUE THREAD

**Issue by tomerb15** [wix/wix-restaurants-js-sdk#3]
Hey,
When submitting an order with chargeV2, i get the following Error:
condition for charge d6c84bf3-8c8a-497d-88cf-975c9b7face7 is not satisfied

The chargeV2 is defined with the following conditions:
- 10% off All Items
- Active on Openning Hours (Which are 24/7)
- Active on mobileweb and web (All options available for selection on wix.com)
- Active on both Delivery and Pickup

More Info:
- `orderHelper.getOrderCharges` returns the correct discount amount
- The array returned from `orderHelper.getOrderCharges` is passed AS IS to `order.orderCharges`

Any idea what might be the problem?

**Comment by dleshem** [comment]
This error means that one of the charge conditions was not satisfied for the submitted order.

Make sure you pass to `orderHelper.getOrderCharges` the same parameters that you later use when submitting the order, e.g. platform, source.

**Comment by tomerb15** [comment]
the platform i'm sending is `com.facebook` while the available platforms for a charge are:
web
mobileweb

regarding the "source" i have no source condition on the charge.

**Comment by dleshem** [comment]
Yes, the Wix Restaurants dashboard UI currently does not support setting up discounts for bot platforms.

There are two ways to work around this-

1. when submitting the order, set `Order.platform` to `mobileweb` platform instaed of `com.messenger` (you mistakenly wrote `com.facebook`). 
2. update the charge to support this platform using the API and not the UI (i.e. `set_menu` request). The charge structure should be easy to figure out from the JSON.

(1) is the fastest option, but the downside is that these orders will not be marked as bot orders. This is not indicated in the UI currently, but may be in the future.

**Comment by tomerb15** [comment]
Do you have an example on how to do 1?
Any link will do...
I found this link but it seems to be broken:
https://github.com/wix/openrest4j/blob/master/openrest4j-api/src/main/java/com/openrest/v1_1/SetMenuRequest.java

**Comment by dleshem** [comment]
This is the correct link: https://github.com/wix/openrest4j/blob/master/openrest4j-api/src/main/java/com/wix/restaurants/requests/SetMenuRequest.java

We don't have a better example, I'm afraid you're on your own on this one...

**Comment by tomerb15** [comment]
How can i generate the `accessToken` for that operation?

**Comment by dleshem** [comment]
See here: http://developers.wixrestaurants.com/Authorization
