### ISSUE TITLE
Automated Token Generation

### ISSUE THREAD

**Issue by tomerb15** [wix/wix-restaurants-js-sdk#5]
Hi,

Say i have a username and a password for a wix restaurants account,
How can i automatically generate an access token?

The following link:
http://developers.wixrestaurants.com/Authorization

Explains how to get the instance manually and then generate the accessToken.
Since getting the Instance is something that needs to be done every 48 hours, i was wondering if there is an automated way to do it once i have an account's credentials.

**Comment by dleshem** [comment]
Unfortunately there isn't at the moment. We are aware of how cumbersome this is, and are working on ways to improve the flow - but it will take some time.
