### ISSUE TITLE
Getting ALL organizations under a distributor

### ISSUE THREAD

**Issue by tomerb15** [wix/wix-restaurants-js-sdk#6]
Per Distributor ID, how can i fetch all its organization with their FULL data. ("get_organization_full")

In other words, how can i get all full organizations without fetching them one by one?

**Comment by tomerb15** [comment]
Motivation is to get all menus and all charges objects of all active restaurants at once.

**Comment by dleshem** [comment]
You can aggregate multiple requests with a batch request, e.g.-
```javascript
{
  "type": "batch",
  "requests": [{
    "type": "get_organization_full",
    "organizationId": "organization-id-1"
  }, {
    "type": "get_organization_full",
    "organizationId": "organization-id-2"
  }]
}
```
