### ISSUE TITLE
npm to determine which deliveryInfo is relevant for an Order

### ISSUE THREAD

**Issue by tomerb15** [wix/wix-restaurants-js-sdk#7]
Sometimes more than 1 deliveryInfo match a certain address.
In that case the relevant deliveryInfo we should use is the one that match the order's grand total.

Do you have a NPM Packages that does it?

Thanks!

**Comment by 3LOK** [comment]
Hi, we have this logic in a different internal NPM. I'll copy it into this project in the next few days.

**Comment by 3LOK** [comment]
Hi,

Added a new helper call DeliveryDispatchInfo. You can see it [here](https://github.com/wix/wix-restaurants-js-sdk/blob/master/src/helpers/DeliveryDispatchInfo.js), and usage example in the tests [here](https://github.com/wix/wix-restaurants-js-sdk/blob/master/test/helpers/DeliveryDispatchInfo.test.js). 

You would normally want to use 'fliterAndSort' method, with sorting by charge, and selecting the first delivery area returned.
