### ISSUE TITLE
Helper for Display Conditions

### ISSUE THREAD

**Issue by tomerb15** [wix/wix-restaurants-js-sdk#8]
I have many broken restaurants that are not showing menus, so if possible i'll appreciate a quick help here :)

I have elements such (e.g a menu) that have "displayCondition" on them.
How can i determine if its valid for display or not? Is there an NPM for that?

* For chargesV2 i use the chargeV2Helper.

**Comment by 3LOK** [comment]
Hi,

Use: https://github.com/wix/wix-restaurants-js-sdk/blob/master/src/helpers/Condition.js

 - Yoav.

**Comment by tomerb15** [comment]
Thanks for the quick answer!
The helper you suggested is not part of the last updated NPM.
